name: tismenv
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.19
  - pytorch=2.3.1
  - setuptools=69.5.1
  - pip:
      - joblib==1.4.2
      - llvmlite==0.41.1
      - numba==0.58.1
      - numpy==1.24.4
      - pandas==2.0.3
      - pip==24.1
      - pyfaidx==0.8.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-learn==1.3.2
      - six==1.16.0
      - tangermeme==0.2.1
      - tqdm==4.66.4
      - tzdata==2024.1
      - yuzu-ism==0.0.1
